/**
 * GlareMap bookmarklet bundler — zero dependencies.
 * Concatenates scanner.js + renderer.js + panel.js + bookmarklet.js into one
 * IIFE after stripping ES module `export` keywords, then writes bookmarklet.min.js.
 */
import { readFileSync, writeFileSync } from 'node:fs';

const files = ['scanner.js', 'renderer.js', 'panel.js', 'bookmarklet.js'];

const stripExports = (src) =>
  src.replace(/^export\s+(?=(?:default\s+)?(?:function|class|const|let|var|async))/gm, '');

const code = files
  .map((f) => stripExports(readFileSync(new URL(`./${f}`, import.meta.url), 'utf8')))
  .join('\n\n');

const bundle = `/* GlareMap bookmarklet bundle — generated by build.js, do not edit. */\n(() => {\n${code}\n})();\n`;

writeFileSync(new URL('./bookmarklet.min.js', import.meta.url), bundle);
console.log(`bookmarklet.min.js: ${Buffer.byteLength(bundle)} bytes`);
